/*
 * XMS API
 * XMS is the controller of distributed storage system
 *
 * OpenAPI spec version: XSCALEROS_6.2.000.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package xio.sds.client.api;

import xio.sds.client.model.OSStorageClassCreateReq;
import xio.sds.client.model.OSStorageClassResp;
import xio.sds.client.model.OSStorageClassUpdateReq;
import xio.sds.client.model.OSStorageClassesResp;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for OsStorageClassesApi
 */
@Ignore
public class OsStorageClassesApiTest {

    private final OsStorageClassesApi api = new OsStorageClassesApi();

    /**
     * 
     *
     * Create os storage class
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createOSStorageClassTest() throws Exception {
        OSStorageClassCreateReq body = null;
        String clusterId = null;
        OSStorageClassResp response = api.createOSStorageClass(body, clusterId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Delete an os storage class
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteOSStorageClassTest() throws Exception {
        Long storageClassId = null;
        OSStorageClassResp response = api.deleteOSStorageClass(storageClassId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Get an os storage class
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOSStorageClassTest() throws Exception {
        String storageClassId = null;
        OSStorageClassResp response = api.getOSStorageClass(storageClassId);

        // TODO: test validations
    }
    /**
     * 
     *
     * List os storage classes
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listOSStorageClassesTest() throws Exception {
        Long limit = null;
        Long offset = null;
        Long osPolicyId = null;
        String clusterId = null;
        OSStorageClassesResp response = api.listOSStorageClasses(limit, offset, osPolicyId, clusterId);

        // TODO: test validations
    }
    /**
     * 
     *
     * update storage class
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateOSStorageClassTest() throws Exception {
        OSStorageClassUpdateReq body = null;
        Long storageClassId = null;
        OSStorageClassResp response = api.updateOSStorageClass(body, storageClassId);

        // TODO: test validations
    }
}
