/*
 * XMS API
 * XMS is the controller of distributed storage system
 *
 * OpenAPI spec version: XSCALEROS_6.2.000.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package xio.sds.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * CloudExtraProperties contains extra properties
 */
@Schema(description = "CloudExtraProperties contains extra properties")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T09:00:29.487Z[GMT]")
public class CloudExtraProperties {
  @SerializedName("csi_driver_versions")
  private List<String> csiDriverVersions = null;

  @SerializedName("domain_id")
  private String domainId = null;

  @SerializedName("domain_name")
  private String domainName = null;

  @SerializedName("k8s_version")
  private String k8sVersion = null;

  @SerializedName("regions")
  private List<String> regions = null;

  @SerializedName("tenant_id")
  private String tenantId = null;

  @SerializedName("tenant_name")
  private String tenantName = null;

  public CloudExtraProperties csiDriverVersions(List<String> csiDriverVersions) {
    this.csiDriverVersions = csiDriverVersions;
    return this;
  }

  public CloudExtraProperties addCsiDriverVersionsItem(String csiDriverVersionsItem) {
    if (this.csiDriverVersions == null) {
      this.csiDriverVersions = new ArrayList<String>();
    }
    this.csiDriverVersions.add(csiDriverVersionsItem);
    return this;
  }

   /**
   * csi driver versions
   * @return csiDriverVersions
  **/
  @Schema(description = "csi driver versions")
  public List<String> getCsiDriverVersions() {
    return csiDriverVersions;
  }

  public void setCsiDriverVersions(List<String> csiDriverVersions) {
    this.csiDriverVersions = csiDriverVersions;
  }

  public CloudExtraProperties domainId(String domainId) {
    this.domainId = domainId;
    return this;
  }

   /**
   * domain id for openstack
   * @return domainId
  **/
  @Schema(description = "domain id for openstack")
  public String getDomainId() {
    return domainId;
  }

  public void setDomainId(String domainId) {
    this.domainId = domainId;
  }

  public CloudExtraProperties domainName(String domainName) {
    this.domainName = domainName;
    return this;
  }

   /**
   * domain name for openstack
   * @return domainName
  **/
  @Schema(description = "domain name for openstack")
  public String getDomainName() {
    return domainName;
  }

  public void setDomainName(String domainName) {
    this.domainName = domainName;
  }

  public CloudExtraProperties k8sVersion(String k8sVersion) {
    this.k8sVersion = k8sVersion;
    return this;
  }

   /**
   * kubernetes version
   * @return k8sVersion
  **/
  @Schema(description = "kubernetes version")
  public String getK8sVersion() {
    return k8sVersion;
  }

  public void setK8sVersion(String k8sVersion) {
    this.k8sVersion = k8sVersion;
  }

  public CloudExtraProperties regions(List<String> regions) {
    this.regions = regions;
    return this;
  }

  public CloudExtraProperties addRegionsItem(String regionsItem) {
    if (this.regions == null) {
      this.regions = new ArrayList<String>();
    }
    this.regions.add(regionsItem);
    return this;
  }

   /**
   * regions for openstack
   * @return regions
  **/
  @Schema(description = "regions for openstack")
  public List<String> getRegions() {
    return regions;
  }

  public void setRegions(List<String> regions) {
    this.regions = regions;
  }

  public CloudExtraProperties tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * tenant id for openstack
   * @return tenantId
  **/
  @Schema(description = "tenant id for openstack")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public CloudExtraProperties tenantName(String tenantName) {
    this.tenantName = tenantName;
    return this;
  }

   /**
   * tenant name for openstack
   * @return tenantName
  **/
  @Schema(description = "tenant name for openstack")
  public String getTenantName() {
    return tenantName;
  }

  public void setTenantName(String tenantName) {
    this.tenantName = tenantName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudExtraProperties cloudExtraProperties = (CloudExtraProperties) o;
    return Objects.equals(this.csiDriverVersions, cloudExtraProperties.csiDriverVersions) &&
        Objects.equals(this.domainId, cloudExtraProperties.domainId) &&
        Objects.equals(this.domainName, cloudExtraProperties.domainName) &&
        Objects.equals(this.k8sVersion, cloudExtraProperties.k8sVersion) &&
        Objects.equals(this.regions, cloudExtraProperties.regions) &&
        Objects.equals(this.tenantId, cloudExtraProperties.tenantId) &&
        Objects.equals(this.tenantName, cloudExtraProperties.tenantName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(csiDriverVersions, domainId, domainName, k8sVersion, regions, tenantId, tenantName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudExtraProperties {\n");
    
    sb.append("    csiDriverVersions: ").append(toIndentedString(csiDriverVersions)).append("\n");
    sb.append("    domainId: ").append(toIndentedString(domainId)).append("\n");
    sb.append("    domainName: ").append(toIndentedString(domainName)).append("\n");
    sb.append("    k8sVersion: ").append(toIndentedString(k8sVersion)).append("\n");
    sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    tenantName: ").append(toIndentedString(tenantName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
