/*
 * XMS API
 * XMS is the controller of distributed storage system
 *
 * OpenAPI spec version: XSCALEROS_6.2.000.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package xio.sds.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ConsistentSnapshotNestview
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T09:00:29.487Z[GMT]")
public class ConsistentSnapshotNestview {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("snap_name")
  private String snapName = null;

  public ConsistentSnapshotNestview id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ConsistentSnapshotNestview snapName(String snapName) {
    this.snapName = snapName;
    return this;
  }

   /**
   * Get snapName
   * @return snapName
  **/
  @Schema(description = "")
  public String getSnapName() {
    return snapName;
  }

  public void setSnapName(String snapName) {
    this.snapName = snapName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsistentSnapshotNestview consistentSnapshotNestview = (ConsistentSnapshotNestview) o;
    return Objects.equals(this.id, consistentSnapshotNestview.id) &&
        Objects.equals(this.snapName, consistentSnapshotNestview.snapName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, snapName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsistentSnapshotNestview {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    snapName: ").append(toIndentedString(snapName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
