/*
 * XMS API
 * XMS is the controller of distributed storage system
 *
 * OpenAPI spec version: XSCALEROS_6.2.000.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package xio.sds.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import xio.sds.client.model.DfsGatewayReq;
/**
 * DfsGatewayZoneCreateReqGatewayZone
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T09:00:29.487Z[GMT]")
public class DfsGatewayZoneCreateReqGatewayZone {
  @SerializedName("dfs_gateway_group_id")
  private Long dfsGatewayGroupId = null;

  @SerializedName("dfs_gateways")
  private List<DfsGatewayReq> dfsGateways = new ArrayList<DfsGatewayReq>();

  @SerializedName("dfs_vip_gateways")
  private List<String> dfsVipGateways = null;

  @SerializedName("dfs_vips")
  private List<String> dfsVips = new ArrayList<String>();

  @SerializedName("name")
  private String name = null;

  public DfsGatewayZoneCreateReqGatewayZone dfsGatewayGroupId(Long dfsGatewayGroupId) {
    this.dfsGatewayGroupId = dfsGatewayGroupId;
    return this;
  }

   /**
   * id of dfs gateway group
   * @return dfsGatewayGroupId
  **/
  @Schema(required = true, description = "id of dfs gateway group")
  public Long getDfsGatewayGroupId() {
    return dfsGatewayGroupId;
  }

  public void setDfsGatewayGroupId(Long dfsGatewayGroupId) {
    this.dfsGatewayGroupId = dfsGatewayGroupId;
  }

  public DfsGatewayZoneCreateReqGatewayZone dfsGateways(List<DfsGatewayReq> dfsGateways) {
    this.dfsGateways = dfsGateways;
    return this;
  }

  public DfsGatewayZoneCreateReqGatewayZone addDfsGatewaysItem(DfsGatewayReq dfsGatewaysItem) {
    this.dfsGateways.add(dfsGatewaysItem);
    return this;
  }

   /**
   * dfs gateways list
   * @return dfsGateways
  **/
  @Schema(required = true, description = "dfs gateways list")
  public List<DfsGatewayReq> getDfsGateways() {
    return dfsGateways;
  }

  public void setDfsGateways(List<DfsGatewayReq> dfsGateways) {
    this.dfsGateways = dfsGateways;
  }

  public DfsGatewayZoneCreateReqGatewayZone dfsVipGateways(List<String> dfsVipGateways) {
    this.dfsVipGateways = dfsVipGateways;
    return this;
  }

  public DfsGatewayZoneCreateReqGatewayZone addDfsVipGatewaysItem(String dfsVipGatewaysItem) {
    if (this.dfsVipGateways == null) {
      this.dfsVipGateways = new ArrayList<String>();
    }
    this.dfsVipGateways.add(dfsVipGatewaysItem);
    return this;
  }

   /**
   * vip gateway list
   * @return dfsVipGateways
  **/
  @Schema(description = "vip gateway list")
  public List<String> getDfsVipGateways() {
    return dfsVipGateways;
  }

  public void setDfsVipGateways(List<String> dfsVipGateways) {
    this.dfsVipGateways = dfsVipGateways;
  }

  public DfsGatewayZoneCreateReqGatewayZone dfsVips(List<String> dfsVips) {
    this.dfsVips = dfsVips;
    return this;
  }

  public DfsGatewayZoneCreateReqGatewayZone addDfsVipsItem(String dfsVipsItem) {
    this.dfsVips.add(dfsVipsItem);
    return this;
  }

   /**
   * vip list
   * @return dfsVips
  **/
  @Schema(required = true, description = "vip list")
  public List<String> getDfsVips() {
    return dfsVips;
  }

  public void setDfsVips(List<String> dfsVips) {
    this.dfsVips = dfsVips;
  }

  public DfsGatewayZoneCreateReqGatewayZone name(String name) {
    this.name = name;
    return this;
  }

   /**
   * gateway zone name
   * @return name
  **/
  @Schema(required = true, description = "gateway zone name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DfsGatewayZoneCreateReqGatewayZone dfsGatewayZoneCreateReqGatewayZone = (DfsGatewayZoneCreateReqGatewayZone) o;
    return Objects.equals(this.dfsGatewayGroupId, dfsGatewayZoneCreateReqGatewayZone.dfsGatewayGroupId) &&
        Objects.equals(this.dfsGateways, dfsGatewayZoneCreateReqGatewayZone.dfsGateways) &&
        Objects.equals(this.dfsVipGateways, dfsGatewayZoneCreateReqGatewayZone.dfsVipGateways) &&
        Objects.equals(this.dfsVips, dfsGatewayZoneCreateReqGatewayZone.dfsVips) &&
        Objects.equals(this.name, dfsGatewayZoneCreateReqGatewayZone.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dfsGatewayGroupId, dfsGateways, dfsVipGateways, dfsVips, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DfsGatewayZoneCreateReqGatewayZone {\n");
    
    sb.append("    dfsGatewayGroupId: ").append(toIndentedString(dfsGatewayGroupId)).append("\n");
    sb.append("    dfsGateways: ").append(toIndentedString(dfsGateways)).append("\n");
    sb.append("    dfsVipGateways: ").append(toIndentedString(dfsVipGateways)).append("\n");
    sb.append("    dfsVips: ").append(toIndentedString(dfsVips)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
