/*
 * XMS API
 * XMS is the controller of distributed storage system
 *
 * OpenAPI spec version: XSCALEROS_6.2.000.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package xio.sds.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import xio.sds.client.model.DfsQuotaRecord;
/**
 * DfsQuotasResp
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T09:00:29.487Z[GMT]")
public class DfsQuotasResp {
  @SerializedName("dfs_quotas")
  private List<DfsQuotaRecord> dfsQuotas = null;

  public DfsQuotasResp dfsQuotas(List<DfsQuotaRecord> dfsQuotas) {
    this.dfsQuotas = dfsQuotas;
    return this;
  }

  public DfsQuotasResp addDfsQuotasItem(DfsQuotaRecord dfsQuotasItem) {
    if (this.dfsQuotas == null) {
      this.dfsQuotas = new ArrayList<DfsQuotaRecord>();
    }
    this.dfsQuotas.add(dfsQuotasItem);
    return this;
  }

   /**
   * dfs quota records
   * @return dfsQuotas
  **/
  @Schema(description = "dfs quota records")
  public List<DfsQuotaRecord> getDfsQuotas() {
    return dfsQuotas;
  }

  public void setDfsQuotas(List<DfsQuotaRecord> dfsQuotas) {
    this.dfsQuotas = dfsQuotas;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DfsQuotasResp dfsQuotasResp = (DfsQuotasResp) o;
    return Objects.equals(this.dfsQuotas, dfsQuotasResp.dfsQuotas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dfsQuotas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DfsQuotasResp {\n");
    
    sb.append("    dfsQuotas: ").append(toIndentedString(dfsQuotas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
