/*
 * XMS API
 * XMS is the controller of distributed storage system
 *
 * OpenAPI spec version: XSCALEROS_6.2.000.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package xio.sds.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DfsSMBShareUpdateACLReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T09:00:29.487Z[GMT]")
public class DfsSMBShareUpdateACLReq {
  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("permission")
  private String permission = null;

  public DfsSMBShareUpdateACLReq description(String description) {
    this.description = description;
    return this;
  }

   /**
   * description of user or user group
   * @return description
  **/
  @Schema(description = "description of user or user group")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DfsSMBShareUpdateACLReq id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * id of user group
   * @return id
  **/
  @Schema(description = "id of user group")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public DfsSMBShareUpdateACLReq permission(String permission) {
    this.permission = permission;
    return this;
  }

   /**
   * readonly or readwrite access
   * @return permission
  **/
  @Schema(description = "readonly or readwrite access")
  public String getPermission() {
    return permission;
  }

  public void setPermission(String permission) {
    this.permission = permission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DfsSMBShareUpdateACLReq dfsSMBShareUpdateACLReq = (DfsSMBShareUpdateACLReq) o;
    return Objects.equals(this.description, dfsSMBShareUpdateACLReq.description) &&
        Objects.equals(this.id, dfsSMBShareUpdateACLReq.id) &&
        Objects.equals(this.permission, dfsSMBShareUpdateACLReq.permission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, id, permission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DfsSMBShareUpdateACLReq {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
