/*
 * XMS API
 * XMS is the controller of distributed storage system
 *
 * OpenAPI spec version: XSCALEROS_6.2.000.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package xio.sds.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OspBucketReplicationStat
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T09:00:29.487Z[GMT]")
public class OspBucketReplicationStat {
  @SerializedName("replication_del_latency_us")
  private Double replicationDelLatencyUs = null;

  @SerializedName("total_bandwidth_kbyte")
  private Double totalBandwidthKbyte = null;

  @SerializedName("total_ops")
  private Long totalOps = null;

  @SerializedName("create")
  private String create = null;

  @SerializedName("replication_ops_pm")
  private Double replicationOpsPm = null;

  @SerializedName("replication_ops")
  private Long replicationOps = null;

  @SerializedName("total_latency")
  private Long totalLatency = null;

  @SerializedName("replication_del_ops_pm")
  private Double replicationDelOpsPm = null;

  @SerializedName("replication_latency_us")
  private Double replicationLatencyUs = null;

  @SerializedName("total_ops_pm")
  private Double totalOpsPm = null;

  @SerializedName("replication_del_latency")
  private Long replicationDelLatency = null;

  @SerializedName("total_latency_us")
  private Double totalLatencyUs = null;

  @SerializedName("replication_latency")
  private Long replicationLatency = null;

  @SerializedName("replication_del_ops")
  private Long replicationDelOps = null;

  @SerializedName("total_bytes")
  private Long totalBytes = null;

  public OspBucketReplicationStat replicationDelLatencyUs(Double replicationDelLatencyUs) {
    this.replicationDelLatencyUs = replicationDelLatencyUs;
    return this;
  }

   /**
   * Get replicationDelLatencyUs
   * @return replicationDelLatencyUs
  **/
  @Schema(description = "")
  public Double getReplicationDelLatencyUs() {
    return replicationDelLatencyUs;
  }

  public void setReplicationDelLatencyUs(Double replicationDelLatencyUs) {
    this.replicationDelLatencyUs = replicationDelLatencyUs;
  }

  public OspBucketReplicationStat totalBandwidthKbyte(Double totalBandwidthKbyte) {
    this.totalBandwidthKbyte = totalBandwidthKbyte;
    return this;
  }

   /**
   * Get totalBandwidthKbyte
   * @return totalBandwidthKbyte
  **/
  @Schema(description = "")
  public Double getTotalBandwidthKbyte() {
    return totalBandwidthKbyte;
  }

  public void setTotalBandwidthKbyte(Double totalBandwidthKbyte) {
    this.totalBandwidthKbyte = totalBandwidthKbyte;
  }

  public OspBucketReplicationStat totalOps(Long totalOps) {
    this.totalOps = totalOps;
    return this;
  }

   /**
   * Get totalOps
   * @return totalOps
  **/
  @Schema(description = "")
  public Long getTotalOps() {
    return totalOps;
  }

  public void setTotalOps(Long totalOps) {
    this.totalOps = totalOps;
  }

  public OspBucketReplicationStat create(String create) {
    this.create = create;
    return this;
  }

   /**
   * Get create
   * @return create
  **/
  @Schema(description = "")
  public String getCreate() {
    return create;
  }

  public void setCreate(String create) {
    this.create = create;
  }

  public OspBucketReplicationStat replicationOpsPm(Double replicationOpsPm) {
    this.replicationOpsPm = replicationOpsPm;
    return this;
  }

   /**
   * Get replicationOpsPm
   * @return replicationOpsPm
  **/
  @Schema(description = "")
  public Double getReplicationOpsPm() {
    return replicationOpsPm;
  }

  public void setReplicationOpsPm(Double replicationOpsPm) {
    this.replicationOpsPm = replicationOpsPm;
  }

  public OspBucketReplicationStat replicationOps(Long replicationOps) {
    this.replicationOps = replicationOps;
    return this;
  }

   /**
   * Get replicationOps
   * @return replicationOps
  **/
  @Schema(description = "")
  public Long getReplicationOps() {
    return replicationOps;
  }

  public void setReplicationOps(Long replicationOps) {
    this.replicationOps = replicationOps;
  }

  public OspBucketReplicationStat totalLatency(Long totalLatency) {
    this.totalLatency = totalLatency;
    return this;
  }

   /**
   * Get totalLatency
   * @return totalLatency
  **/
  @Schema(description = "")
  public Long getTotalLatency() {
    return totalLatency;
  }

  public void setTotalLatency(Long totalLatency) {
    this.totalLatency = totalLatency;
  }

  public OspBucketReplicationStat replicationDelOpsPm(Double replicationDelOpsPm) {
    this.replicationDelOpsPm = replicationDelOpsPm;
    return this;
  }

   /**
   * Get replicationDelOpsPm
   * @return replicationDelOpsPm
  **/
  @Schema(description = "")
  public Double getReplicationDelOpsPm() {
    return replicationDelOpsPm;
  }

  public void setReplicationDelOpsPm(Double replicationDelOpsPm) {
    this.replicationDelOpsPm = replicationDelOpsPm;
  }

  public OspBucketReplicationStat replicationLatencyUs(Double replicationLatencyUs) {
    this.replicationLatencyUs = replicationLatencyUs;
    return this;
  }

   /**
   * Get replicationLatencyUs
   * @return replicationLatencyUs
  **/
  @Schema(description = "")
  public Double getReplicationLatencyUs() {
    return replicationLatencyUs;
  }

  public void setReplicationLatencyUs(Double replicationLatencyUs) {
    this.replicationLatencyUs = replicationLatencyUs;
  }

  public OspBucketReplicationStat totalOpsPm(Double totalOpsPm) {
    this.totalOpsPm = totalOpsPm;
    return this;
  }

   /**
   * Get totalOpsPm
   * @return totalOpsPm
  **/
  @Schema(description = "")
  public Double getTotalOpsPm() {
    return totalOpsPm;
  }

  public void setTotalOpsPm(Double totalOpsPm) {
    this.totalOpsPm = totalOpsPm;
  }

  public OspBucketReplicationStat replicationDelLatency(Long replicationDelLatency) {
    this.replicationDelLatency = replicationDelLatency;
    return this;
  }

   /**
   * Get replicationDelLatency
   * @return replicationDelLatency
  **/
  @Schema(description = "")
  public Long getReplicationDelLatency() {
    return replicationDelLatency;
  }

  public void setReplicationDelLatency(Long replicationDelLatency) {
    this.replicationDelLatency = replicationDelLatency;
  }

  public OspBucketReplicationStat totalLatencyUs(Double totalLatencyUs) {
    this.totalLatencyUs = totalLatencyUs;
    return this;
  }

   /**
   * Get totalLatencyUs
   * @return totalLatencyUs
  **/
  @Schema(description = "")
  public Double getTotalLatencyUs() {
    return totalLatencyUs;
  }

  public void setTotalLatencyUs(Double totalLatencyUs) {
    this.totalLatencyUs = totalLatencyUs;
  }

  public OspBucketReplicationStat replicationLatency(Long replicationLatency) {
    this.replicationLatency = replicationLatency;
    return this;
  }

   /**
   * Get replicationLatency
   * @return replicationLatency
  **/
  @Schema(description = "")
  public Long getReplicationLatency() {
    return replicationLatency;
  }

  public void setReplicationLatency(Long replicationLatency) {
    this.replicationLatency = replicationLatency;
  }

  public OspBucketReplicationStat replicationDelOps(Long replicationDelOps) {
    this.replicationDelOps = replicationDelOps;
    return this;
  }

   /**
   * Get replicationDelOps
   * @return replicationDelOps
  **/
  @Schema(description = "")
  public Long getReplicationDelOps() {
    return replicationDelOps;
  }

  public void setReplicationDelOps(Long replicationDelOps) {
    this.replicationDelOps = replicationDelOps;
  }

  public OspBucketReplicationStat totalBytes(Long totalBytes) {
    this.totalBytes = totalBytes;
    return this;
  }

   /**
   * Get totalBytes
   * @return totalBytes
  **/
  @Schema(description = "")
  public Long getTotalBytes() {
    return totalBytes;
  }

  public void setTotalBytes(Long totalBytes) {
    this.totalBytes = totalBytes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OspBucketReplicationStat ospBucketReplicationStat = (OspBucketReplicationStat) o;
    return Objects.equals(this.replicationDelLatencyUs, ospBucketReplicationStat.replicationDelLatencyUs) &&
        Objects.equals(this.totalBandwidthKbyte, ospBucketReplicationStat.totalBandwidthKbyte) &&
        Objects.equals(this.totalOps, ospBucketReplicationStat.totalOps) &&
        Objects.equals(this.create, ospBucketReplicationStat.create) &&
        Objects.equals(this.replicationOpsPm, ospBucketReplicationStat.replicationOpsPm) &&
        Objects.equals(this.replicationOps, ospBucketReplicationStat.replicationOps) &&
        Objects.equals(this.totalLatency, ospBucketReplicationStat.totalLatency) &&
        Objects.equals(this.replicationDelOpsPm, ospBucketReplicationStat.replicationDelOpsPm) &&
        Objects.equals(this.replicationLatencyUs, ospBucketReplicationStat.replicationLatencyUs) &&
        Objects.equals(this.totalOpsPm, ospBucketReplicationStat.totalOpsPm) &&
        Objects.equals(this.replicationDelLatency, ospBucketReplicationStat.replicationDelLatency) &&
        Objects.equals(this.totalLatencyUs, ospBucketReplicationStat.totalLatencyUs) &&
        Objects.equals(this.replicationLatency, ospBucketReplicationStat.replicationLatency) &&
        Objects.equals(this.replicationDelOps, ospBucketReplicationStat.replicationDelOps) &&
        Objects.equals(this.totalBytes, ospBucketReplicationStat.totalBytes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(replicationDelLatencyUs, totalBandwidthKbyte, totalOps, create, replicationOpsPm, replicationOps, totalLatency, replicationDelOpsPm, replicationLatencyUs, totalOpsPm, replicationDelLatency, totalLatencyUs, replicationLatency, replicationDelOps, totalBytes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OspBucketReplicationStat {\n");
    
    sb.append("    replicationDelLatencyUs: ").append(toIndentedString(replicationDelLatencyUs)).append("\n");
    sb.append("    totalBandwidthKbyte: ").append(toIndentedString(totalBandwidthKbyte)).append("\n");
    sb.append("    totalOps: ").append(toIndentedString(totalOps)).append("\n");
    sb.append("    create: ").append(toIndentedString(create)).append("\n");
    sb.append("    replicationOpsPm: ").append(toIndentedString(replicationOpsPm)).append("\n");
    sb.append("    replicationOps: ").append(toIndentedString(replicationOps)).append("\n");
    sb.append("    totalLatency: ").append(toIndentedString(totalLatency)).append("\n");
    sb.append("    replicationDelOpsPm: ").append(toIndentedString(replicationDelOpsPm)).append("\n");
    sb.append("    replicationLatencyUs: ").append(toIndentedString(replicationLatencyUs)).append("\n");
    sb.append("    totalOpsPm: ").append(toIndentedString(totalOpsPm)).append("\n");
    sb.append("    replicationDelLatency: ").append(toIndentedString(replicationDelLatency)).append("\n");
    sb.append("    totalLatencyUs: ").append(toIndentedString(totalLatencyUs)).append("\n");
    sb.append("    replicationLatency: ").append(toIndentedString(replicationLatency)).append("\n");
    sb.append("    replicationDelOps: ").append(toIndentedString(replicationDelOps)).append("\n");
    sb.append("    totalBytes: ").append(toIndentedString(totalBytes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
