/*
 * XMS API
 * XMS is the controller of distributed storage system
 *
 * OpenAPI spec version: XSCALEROS_6.2.000.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package xio.sds.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * OSSearchEngineStat contains info of os search engine
 */
@Schema(description = "OSSearchEngineStat contains info of os search engine")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T09:00:29.487Z[GMT]")
public class OSSearchEngineStat {
  @SerializedName("average_meta_query_latency")
  private Double averageMetaQueryLatency = null;

  @SerializedName("create")
  private OffsetDateTime create = null;

  @SerializedName("meta_query_pm")
  private Double metaQueryPm = null;

  @SerializedName("sync_bandwidth_kbyte")
  private Double syncBandwidthKbyte = null;

  @SerializedName("sync_objects_pm")
  private Double syncObjectsPm = null;

  @SerializedName("total_meta_num")
  private Long totalMetaNum = null;

  @SerializedName("total_meta_size_bytes")
  private Long totalMetaSizeBytes = null;

  public OSSearchEngineStat averageMetaQueryLatency(Double averageMetaQueryLatency) {
    this.averageMetaQueryLatency = averageMetaQueryLatency;
    return this;
  }

   /**
   * Get averageMetaQueryLatency
   * @return averageMetaQueryLatency
  **/
  @Schema(description = "")
  public Double getAverageMetaQueryLatency() {
    return averageMetaQueryLatency;
  }

  public void setAverageMetaQueryLatency(Double averageMetaQueryLatency) {
    this.averageMetaQueryLatency = averageMetaQueryLatency;
  }

  public OSSearchEngineStat create(OffsetDateTime create) {
    this.create = create;
    return this;
  }

   /**
   * Get create
   * @return create
  **/
  @Schema(description = "")
  public OffsetDateTime getCreate() {
    return create;
  }

  public void setCreate(OffsetDateTime create) {
    this.create = create;
  }

  public OSSearchEngineStat metaQueryPm(Double metaQueryPm) {
    this.metaQueryPm = metaQueryPm;
    return this;
  }

   /**
   * Get metaQueryPm
   * @return metaQueryPm
  **/
  @Schema(description = "")
  public Double getMetaQueryPm() {
    return metaQueryPm;
  }

  public void setMetaQueryPm(Double metaQueryPm) {
    this.metaQueryPm = metaQueryPm;
  }

  public OSSearchEngineStat syncBandwidthKbyte(Double syncBandwidthKbyte) {
    this.syncBandwidthKbyte = syncBandwidthKbyte;
    return this;
  }

   /**
   * Get syncBandwidthKbyte
   * @return syncBandwidthKbyte
  **/
  @Schema(description = "")
  public Double getSyncBandwidthKbyte() {
    return syncBandwidthKbyte;
  }

  public void setSyncBandwidthKbyte(Double syncBandwidthKbyte) {
    this.syncBandwidthKbyte = syncBandwidthKbyte;
  }

  public OSSearchEngineStat syncObjectsPm(Double syncObjectsPm) {
    this.syncObjectsPm = syncObjectsPm;
    return this;
  }

   /**
   * Get syncObjectsPm
   * @return syncObjectsPm
  **/
  @Schema(description = "")
  public Double getSyncObjectsPm() {
    return syncObjectsPm;
  }

  public void setSyncObjectsPm(Double syncObjectsPm) {
    this.syncObjectsPm = syncObjectsPm;
  }

  public OSSearchEngineStat totalMetaNum(Long totalMetaNum) {
    this.totalMetaNum = totalMetaNum;
    return this;
  }

   /**
   * Get totalMetaNum
   * @return totalMetaNum
  **/
  @Schema(description = "")
  public Long getTotalMetaNum() {
    return totalMetaNum;
  }

  public void setTotalMetaNum(Long totalMetaNum) {
    this.totalMetaNum = totalMetaNum;
  }

  public OSSearchEngineStat totalMetaSizeBytes(Long totalMetaSizeBytes) {
    this.totalMetaSizeBytes = totalMetaSizeBytes;
    return this;
  }

   /**
   * Get totalMetaSizeBytes
   * @return totalMetaSizeBytes
  **/
  @Schema(description = "")
  public Long getTotalMetaSizeBytes() {
    return totalMetaSizeBytes;
  }

  public void setTotalMetaSizeBytes(Long totalMetaSizeBytes) {
    this.totalMetaSizeBytes = totalMetaSizeBytes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OSSearchEngineStat osSearchEngineStat = (OSSearchEngineStat) o;
    return Objects.equals(this.averageMetaQueryLatency, osSearchEngineStat.averageMetaQueryLatency) &&
        Objects.equals(this.create, osSearchEngineStat.create) &&
        Objects.equals(this.metaQueryPm, osSearchEngineStat.metaQueryPm) &&
        Objects.equals(this.syncBandwidthKbyte, osSearchEngineStat.syncBandwidthKbyte) &&
        Objects.equals(this.syncObjectsPm, osSearchEngineStat.syncObjectsPm) &&
        Objects.equals(this.totalMetaNum, osSearchEngineStat.totalMetaNum) &&
        Objects.equals(this.totalMetaSizeBytes, osSearchEngineStat.totalMetaSizeBytes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(averageMetaQueryLatency, create, metaQueryPm, syncBandwidthKbyte, syncObjectsPm, totalMetaNum, totalMetaSizeBytes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OSSearchEngineStat {\n");
    
    sb.append("    averageMetaQueryLatency: ").append(toIndentedString(averageMetaQueryLatency)).append("\n");
    sb.append("    create: ").append(toIndentedString(create)).append("\n");
    sb.append("    metaQueryPm: ").append(toIndentedString(metaQueryPm)).append("\n");
    sb.append("    syncBandwidthKbyte: ").append(toIndentedString(syncBandwidthKbyte)).append("\n");
    sb.append("    syncObjectsPm: ").append(toIndentedString(syncObjectsPm)).append("\n");
    sb.append("    totalMetaNum: ").append(toIndentedString(totalMetaNum)).append("\n");
    sb.append("    totalMetaSizeBytes: ").append(toIndentedString(totalMetaSizeBytes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
