/*
 * XMS API
 * XMS is the controller of distributed storage system
 *
 * OpenAPI spec version: XSCALEROS_6.2.000.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package xio.sds.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SetOsdFullRatioReqOsdGroup
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T09:00:29.487Z[GMT]")
public class SetOsdFullRatioReqOsdGroup {
  @SerializedName("osd_full_ratio")
  private Double osdFullRatio = null;

  public SetOsdFullRatioReqOsdGroup osdFullRatio(Double osdFullRatio) {
    this.osdFullRatio = osdFullRatio;
    return this;
  }

   /**
   * Get osdFullRatio
   * @return osdFullRatio
  **/
  @Schema(required = true, description = "")
  public Double getOsdFullRatio() {
    return osdFullRatio;
  }

  public void setOsdFullRatio(Double osdFullRatio) {
    this.osdFullRatio = osdFullRatio;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetOsdFullRatioReqOsdGroup setOsdFullRatioReqOsdGroup = (SetOsdFullRatioReqOsdGroup) o;
    return Objects.equals(this.osdFullRatio, setOsdFullRatioReqOsdGroup.osdFullRatio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(osdFullRatio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetOsdFullRatioReqOsdGroup {\n");
    
    sb.append("    osdFullRatio: ").append(toIndentedString(osdFullRatio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
