package com.fit2cloud.oss.base.mapper;

import com.fit2cloud.oss.base.domain.FsConfiguration;
import com.fit2cloud.oss.base.domain.FsConfigurationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FsConfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    long countByExample(FsConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    int deleteByExample(FsConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    int insert(FsConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    int insertSelective(FsConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    List<FsConfiguration> selectByExampleWithBLOBs(FsConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    List<FsConfiguration> selectByExample(FsConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    FsConfiguration selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FsConfiguration record, @Param("example") FsConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FsConfiguration record, @Param("example") FsConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FsConfiguration record, @Param("example") FsConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FsConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FsConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FsConfiguration record);
}