package com.fit2cloud.oss.base.mapper;

import com.fit2cloud.oss.base.domain.FsXskyClientGroup;
import com.fit2cloud.oss.base.domain.FsXskyClientGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FsXskyClientGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    long countByExample(FsXskyClientGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    int deleteByExample(FsXskyClientGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    int insert(FsXskyClientGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    int insertSelective(FsXskyClientGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    List<FsXskyClientGroup> selectByExampleWithBLOBs(FsXskyClientGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    List<FsXskyClientGroup> selectByExample(FsXskyClientGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    FsXskyClientGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FsXskyClientGroup record, @Param("example") FsXskyClientGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FsXskyClientGroup record, @Param("example") FsXskyClientGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FsXskyClientGroup record, @Param("example") FsXskyClientGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FsXskyClientGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FsXskyClientGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_client_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FsXskyClientGroup record);
}