package com.fit2cloud.oss.base.mapper;

import com.fit2cloud.oss.base.domain.FsXskyGatewayGroup;
import com.fit2cloud.oss.base.domain.FsXskyGatewayGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FsXskyGatewayGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_gateway_group
     *
     * @mbg.generated
     */
    long countByExample(FsXskyGatewayGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_gateway_group
     *
     * @mbg.generated
     */
    int deleteByExample(FsXskyGatewayGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_gateway_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_gateway_group
     *
     * @mbg.generated
     */
    int insert(FsXskyGatewayGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_gateway_group
     *
     * @mbg.generated
     */
    int insertSelective(FsXskyGatewayGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_gateway_group
     *
     * @mbg.generated
     */
    List<FsXskyGatewayGroup> selectByExample(FsXskyGatewayGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_gateway_group
     *
     * @mbg.generated
     */
    FsXskyGatewayGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_gateway_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FsXskyGatewayGroup record, @Param("example") FsXskyGatewayGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_gateway_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FsXskyGatewayGroup record, @Param("example") FsXskyGatewayGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_gateway_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FsXskyGatewayGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_xsky_gateway_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FsXskyGatewayGroup record);
}